### ISSUE TITLE
Set the production url of Scienterprise BOINC Server

### ISSUE THREAD

**Issue by dzl84** [scienterprise/ScienterpriseServer#2]
- Set production url to the root of the hostname. Right now http://boinc.scienterprise.cn/scienterprise points to our BOINC server. Expected to move it at http://boinc.scienterprise.cn
- The current base_url is set as host IP in boinc server. Expected to update it to http://boinc.scienterprise.cn

**Comment by Zhe-Shen** [comment]
The new website is now on http://boinc.scienterprise.cn/
